added the file for the part 3 of deploying your stx-app blog-post series
tnpb-encora/blog-post-03 pull request #1
Opened 2024-05-14 12:31 UTC by tnpb-encora

2024-05-14 13:59 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Deploying your application as a StarlingX application is the highest level of integration you can achieve with the platform. It is a step up from deploying an app via [Helm](https://www.starlingx.io/
I feel like we could do this introduction a little bit better. Take a look at the blog posts 1 and 2. First it is introduced all the ways that an application can be deployed and then it goes into the specifics of the method in the post. I also would add the type of configuration your stx have, like if it AIO or not, if it is virtual or bare metal and what release is using.

 Also maybe separate into a different section the information about the demo application

2024-05-14 13:59 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +It is worth noting that while deploying a containerized app as a StarlingX app has its advantages and is easy to do, transforming a containerized application into a StarlingX app might not be. Theref
Not sure I like the statement beginner-friendly. We should take into consideration what Greg said in one of the emails. We don't want user to think that they need to go the extra mile to deploy their user loads using this method. This type of integration is not expected for user loads.

2024-05-14 13:59 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +This tutorial expects that your application will be containerized and with ready helm-charts. If this is not your case, please read the blog post already mentioned about Helm.
The thing is, the previous blog posts also expects the application to be containerized, the posts only guide the deployment and not the process of creating the Helm charts

2024-05-14 14:00 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Some of the advantages of installing an app via system are:
I think this can be better written. What means to be installed via system?

2024-05-14 14:00 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +* My favourite advantage may be that you can upgrade a StarlingX application via system with an updated tar package of that application, and the system will distribute the new version to the other ho
Then again, I think some sort of disclaimer should be added informing that while this type of deployment offers the most integration possible with the STX platform, user loads are not expected to be deployed this way.

2024-05-14 14:00 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +python3 -m venv venv
One thing to consider is, the app-gen-tool it is, now, directly on the starlingx system. meaning you can do all of this directly on the platform without the need to have another system

2024-05-14 14:00 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Next. I'll copy the "helm-chart" folder from the poc-starlingx to the directory I'm currently working on and create an empty file called `app_manifest.yaml`. Here's the folder structure till now:
What is poc-starlingx? It is the first time this name is mentioned in this post, maybe when informing about the application that will be used in this demonstration you can inform that poc-starlingx will be the alias of the application

2024-05-14 14:01 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +and here's a look at the ```app_manifest.yaml``` after its configuration
I think a text should be added just explaining the purpose of creating this app_manifest.yaml file

2024-05-14 14:01 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +As you can see, the helm chart package was packed under the charts subdirectory. The next step would be to configure the plugins, since this is a complicated process and is application-dependent, we
Not only the plugins may need to be changed but also the static-overrides. Like you said it is something really complicated to be explained here, but also the README of the app-gen don't explain this very good, I think the best option is to link the wiki page, the amount of information there can be better suited for explaining to new users this specific process, although even there is not exactly greatly explained

2024-05-14 14:01 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +After copying your app package to your StarlingX cluster(in my case a virtual AIO-SX, we can now proceed to install it. But before installing it, please guarantee that your platform-integ-apps applic
Here, I think this information about your system should be up there where I commented

2024-05-14 14:02 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +system application-show poc-starlingx-app | grep uploaded
maybe remove the grep part, so all the information about the application in the application-show is demonstrated here

2024-05-14 14:02 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +[sysadmin@controller-0 ~(keystone_admin)]$ system application-show poc-starlingx-app | grep applied
same here

2024-05-14 14:02 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +## Troubleshooting
Should this section exist? Since troubleshooting can be so much more than just this, it seems to me that maybe we shouldn't add this.

2024-05-14 14:02 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +### kubernetes pod logs
I think it would be nice to add a conclusion section saying this is the conclusion of the series of posts on deploying applications on the StarlingX platform.

2024-05-14 14:02 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +also note that the infos like the prefix of the pod and the namespace where It will be created and running are written in the helm chart of the application.
Ildiko asked bruno and me to add this section in the end, I think you can go ahead and do the same

# About StarlingX

If you would like to learn more about the project and get involved check the [website](https://www.starlingx.io) for more information or [download the code](https://opendev.org/starlingx) and start to experiment with the platform. If you are already evaluating or using the software please fill out the [user survey](https://openinfrafoundation.formstack.com/forms/starlingx_user_survey) and help the community improve the project based on your feedback.

2024-05-14 14:03 UTC, Danmcaires requested changes
Left some comments on things that I think can be changed or added

2024-05-14 19:29 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Deploying your application as a StarlingX application is the highest level of integration you can achieve with the platform. It is a step up from deploying an app via [Helm](https://www.starlingx.io/
I may include the other methods as for maintaining the pattern from the previous posts of the series, but I initially found that including this information again was not necessary.

I briefly mentioned the demo app, do you really think it is necessary to create a separate section about it?

2024-05-14 19:32 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +It is worth noting that while deploying a containerized app as a StarlingX app has its advantages and is easy to do, transforming a containerized application into a StarlingX app might not be. Theref
fair point. I'll change to "standard approaches"

2024-05-14 19:35 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Some of the advantages of installing an app via system are:
I'll change to "StarlingX Application Package Manager"

2024-05-14 20:06 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +python3 -m venv venv
when I wrote this post, I used a build of the stx-8 release and at the time, the included app-gen-tool had some bugs that I reported to Joshua Reed at the time.

2024-05-14 20:08 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Next. I'll copy the "helm-chart" folder from the poc-starlingx to the directory I'm currently working on and create an empty file called `app_manifest.yaml`. Here's the folder structure till now:
good catch!

2024-05-14 20:16 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +and here's a look at the ```app_manifest.yaml``` after its configuration
done

2024-05-14 22:51 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +As you can see, the helm chart package was packed under the charts subdirectory. The next step would be to configure the plugins, since this is a complicated process and is application-dependent, we
I agree that the wiki is a valuable resource, but does it contain some section explaining about the plugins configurations? I thought that you managed to configure the plugins by doing reverse-engineering on existing applications.

2024-05-14 22:51 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +After copying your app package to your StarlingX cluster(in my case a virtual AIO-SX, we can now proceed to install it. But before installing it, please guarantee that your platform-integ-apps applic
agree

2024-05-14 22:51 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +system application-show poc-starlingx-app | grep uploaded
I'll try to do that

2024-05-14 22:51 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +## Troubleshooting
I think this section can be useful for possible inexperienced users reading the blog post. But i'll add a note that troubleshooting can be more complicated than this.

2024-05-14 22:51 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +also note that the infos like the prefix of the pod and the namespace where It will be created and running are written in the helm chart of the application.
ack

2024-05-16 11:44 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +Deploying your application as a StarlingX application is the highest level of integration you can achieve with the platform. It is a step up from deploying an app via [Helm](https://www.starlingx.io/
Maybe not a separate section, but I would definitely put it in a different paragraph.

2024-05-16 11:53 UTC, Danmcaires commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +As you can see, the helm chart package was packed under the charts subdirectory. The next step would be to configure the plugins, since this is a complicated process and is application-dependent, we
The truth is, there is nothing anywhere explaining how to do this, I guess is OK to leave the README, but the Wiki does have a lot of good information, I would link it too. Don't forget to add the information about the static-overrides, the text on the README is a good one.

2024-05-17 19:14 UTC, tnpb-encora commented on src/pages/blog/starlingx-deploying-your-app-3.md
> +As you can see, the helm chart package was packed under the charts subdirectory. The next step would be to configure the plugins, since this is a complicated process and is application-dependent, we
ok

2024-05-23 17:46 UTC, merged